[package]
name = "rat-package"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["rat"]

[dependencies]
rat = { path = "./rat" }

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
